name: notification_calling_example
description: Demonstrates how to use the notification_calling plugin.

publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  notification_calling:
    path: ../

  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  http: ^0.13.4
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/test.png
